server:
  port: 7071

spring:
  application:
    name: eticket-springcloudgateway-service-01
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: eticket-member
        uri: lb://ETICKET-MEMBER
        predicates:
          - Path=/eticket/**
        filters:
          - StripPrefix=1
          
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://34.85.89.243:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
    # 指定此实例的ip，并且生产环境才打开
    ip-address: 13.251.106.34
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}