#spring:
  #application:
    #name: eticket-discovery-eureka
---
#spring:
  #profiles: eticket1                                 # 指定profile=eticket1
#server:
  #port: 8761
#eureka:
  #instance:
    #hostname: eticket1                               # 指定当profile=eticket1时，主机名是eticket1
  #client:
    #service-url:
      #defaultZone: http://eticket2:8762/eureka/
---
#spring:
  #profiles: eticket2
#server:
  #port: 8762
#eureka:
  #instance:
    #hostname: eticket2
  #client:
    #service-url:
      #defaultZone: http://eticket1:8761/eureka/

server:
  port: 8761
eureka:
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/