version: "2"
services:
  eticket1:      # 默认情况下，其他服务可以使用服务名称连接到该服务。因此，对于peer2的节点，它需要连接http://peer1:8761/eureka/，因此需要配置该服务的名称是peer1。
    image: eticket:eureka1
    container_name: eureka-server1
    hostname: eticket1
    networks: 
      - eureka-net
    ports:
      - "8761:8761"
  eticket2:
    image: eticket:eureka2
    container_name: eureka-server2
    hostname: eticket2
    networks: 
      - eureka-net
    ports:
      - "8762:8762"
networks:
  eureka-net:
    driver: bridge